<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Materials for the MSc Conversion Research Methods 1 and 2 courses at the University of Glasgow School of Psychology &amp; Neuroscience.">
<title>Fundamentals of Quantitative Analysis - 8&nbsp; Correlations</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-t-tests.html" rel="next">
<link href="./07-data-viz.html" rel="prev">
<link href="./images/logos/logo.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-correlation.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlations</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Fundamentals of Quantitative Analysis</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-foreword.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foreword</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-programming-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Programming basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-intro-to-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Intro to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-loading-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Starting with data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-wrangling-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data wrangling 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-wrangling-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data wrangling 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-wrangling-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Wrangling 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-data-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Intro to Data Visualisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-correlation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-t-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Power and Effect Sizes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-missing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Screening Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-visualisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Visualisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">One-way ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-factorial-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a-installing-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Installing <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a1-updating-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Updating packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a2-additional-learning-resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Additional Resources</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a3-How-to-cite-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Citing R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-b-symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Symbols</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-d-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-y-license.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">License</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#set-up-the-data" id="toc-set-up-the-data" class="nav-link active" data-scroll-target="#set-up-the-data"><span class="header-section-number">8.1</span> Set-up the Data</a></li>
  <li><a href="#assumptions-of-the-test" id="toc-assumptions-of-the-test" class="nav-link" data-scroll-target="#assumptions-of-the-test"><span class="header-section-number">8.2</span> Assumptions of the test</a></li>
  <li><a href="#descriptives-of-the-correlation" id="toc-descriptives-of-the-correlation" class="nav-link" data-scroll-target="#descriptives-of-the-correlation"><span class="header-section-number">8.3</span> Descriptives of the Correlation</a></li>
  <li><a href="#inferentials-of-the-correlation" id="toc-inferentials-of-the-correlation" class="nav-link" data-scroll-target="#inferentials-of-the-correlation"><span class="header-section-number">8.4</span> Inferentials of the correlation</a></li>
  <li><a href="#interpreting-output-and-writing-up" id="toc-interpreting-output-and-writing-up" class="nav-link" data-scroll-target="#interpreting-output-and-writing-up"><span class="header-section-number">8.5</span> Interpreting output and writing up</a></li>
  <li><a href="#multiple-correlations" id="toc-multiple-correlations" class="nav-link" data-scroll-target="#multiple-correlations"><span class="header-section-number">8.6</span> Multiple Correlations</a></li>
  <li><a href="#corr-fin" id="toc-corr-fin" class="nav-link" data-scroll-target="#corr-fin"><span class="header-section-number">8.7</span> Finished!</a></li>
  <li><a href="#test-yourself" id="toc-test-yourself" class="nav-link" data-scroll-target="#test-yourself"><span class="header-section-number">8.8</span> Test Yourself</a></li>
  <li><a href="#corr-sols" id="toc-corr-sols" class="nav-link" data-scroll-target="#corr-sols"><span class="header-section-number">8.9</span> Activity solutions</a></li>
  <li><a href="#words-from-this-chapter" id="toc-words-from-this-chapter" class="nav-link" data-scroll-target="#words-from-this-chapter"><span class="header-section-number">8.10</span> Words from this Chapter</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlations</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>So far in this book we have been building your skills and knowledge on data wrangling and you now have the basis for a lot of the work you will do in research. You may think that the tasks we ask you to do will get harder as this course progresses but that isn’t true. The hardest part of working with data is at the very beginning, trying to learn the new terminology, figuring out how to load in data and wrangle it into the format you need. And whilst it may feel like you have not yet covered a lot, it is really worth reflecting on just how far you’ve come in a short time.</p>
<p>For instance, you can now:</p>
<ul>
<li>Understand what functions, arguments, objects, variables, and tibbles are.<br>
</li>
<li>Read data into your working environment for analysis.<br>
</li>
<li>Tidy data into an appropriate format.<br>
</li>
<li>Calculate a range of descriptive statistics.</li>
<li>And Create plots of data.</li>
</ul>
<p>That’s amazing! And to be honest, as you will see, that actually covers a large percentage of what we will do. What we do now is start moving on to actually running some <a class="glossary">inferential<span class="def"></span></a> statistics, where we make inferences about our population of interest from the sample we have collected. Specifically, in this chapter we are going to move on to performing a <a class="glossary">correlation<span class="def"></span></a> and to create a plot to visualise the data. Correlation is a test that measures the relationship between two <a class="glossary">variable<span class="def"></span></a>. In other words, you measure two variables and the correlation analysis tells you whether or not they are related in some manner, either <a class="glossary">positive relationship<span class="def"></span></a> or <a class="glossary">negative relationship<span class="def"></span></a>, and how strong that relationship is - when you discuss a correlation you should always talk about the strength and the direction of the relationship. The figure below shows three examples of correlations just to give an idea:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="09-correlation_files/figure-html/ch10-show-figure-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Schematic examples of extreme bivariate relationships</figcaption></figure>
</div>
</div>
</div>
<p><strong>Note:</strong> When dealing with correlations you should always refer to relationships and not predictions. In a correlation, X does not predict Y, nor does X cause an effect in Y. We will look at different tests in this book where you can take about cause-and-effect and about prediction, but correlation all we can say is whether X and Y are related.</p>
<p>Now, as we said above, to actually carry out a correlation is fairly straightforward and we will show you that today in a little while. The hardest part of correlations is really wrangling the data and interpreting what the results mean. You are going to run a few correlations in this chapter to give you good practice at running and interpreting the relationships between two variables.</p>
<p>In this chapter we will use the examples in <a href="https://drive.google.com/file/d/0B1fyuTuvj3YoaFdUR3FZaXNuNXc/view" target="_blank">Miller and Haden (2013)</a>, Chapter 11, looking at the relationship between four variables: reading ability, intelligence (IQ), the number of minutes per week spent reading at home (Home); and the number of minutes per week spent watching TV at home (TV). We will use this data across a series of tasks to help you understand correlations more. You do not need to read the chapter but hopefully from just the names of the variables you can see in this situation that it would be unethical to manipulate these variables so measuring them as they exist in the environment is most appropriate; hence the use of correlations. And for clarity, this is an example of observational research; all correlations are observational, but not all observational research uses correlations.</p>
<p>Finally, there are two main types of correlations that people tend to think of (though there are more):</p>
<ul>
<li>Pearson’s product-moment correlation (often shortened to the <a class="glossary">Pearson<span class="def">a standardised measure of the linear relationship between two variables</span></a> correlation) and symbolised by <strong>r</strong>
</li>
<li>Spearman’s rank correlation coefficient (often shortened to the <a class="glossary">Spearman<span class="def">a standardised measure of the relationship between two variables that does not assume a linear relationship. Note that the relationship can be linear but it is not required.</span></a> correlation) and symbolised by <strong>rho</strong> or sometimes <span class="math inline">\(r_s\)</span> or sometimes <span class="math inline">\(\rho\)</span>
</li>
</ul>
<p>We will talk a little bit about these two correlations in the work we do today. And we shall begin now!</p>
<section id="set-up-the-data" class="level2" data-number="8.1"><h2 data-number="8.1" class="anchored" data-anchor-id="set-up-the-data">
<span class="header-section-number">8.1</span> Set-up the Data</h2>
<p>As always, the first activity is about getting ourselves ready to analyse the data so try out the steps and if you need help, consult the earlier chapters.</p>
<section id="corr-a1" class="level4" data-number="8.1.0.1"><h4 data-number="8.1.0.1" class="anchored" data-anchor-id="corr-a1">
<span class="header-section-number">8.1.0.1</span> Activity 1: Set-up</h4>
<ul>
<li>Open RStudio and set the working directory to your chapter folder. Ensure the environment is clear.
<ul>
<li>If you’re using the Rserver, avoid a number of issues by restarting the session - click <code>Session</code> - <code>Restart R</code>
</li>
</ul>
</li>
<li>Open a new R Markdown document and save it in your working directory. Call the file “Correlations”.<br>
</li>
<li>Download <a href="MillerHadenData.csv" download="">MillerHadenData.csv</a> and save it in your folder. Make sure that you do not change the file name at all.
<ul>
<li>If you prefer you can download the data in a <a href="data/chpt9/PsyTeachR_FQA_Chpt9-data.zip" target="_blank">zip folder by clicking here</a>
</li>
<li>Remember not to change the file names at all and that <code>data.csv</code> is not the same as <code>data (1).csv</code>.</li>
</ul>
</li>
<li>Delete the default R Markdown welcome text and insert a new code chunk that loads the following packages, in this specific order, using the <code><a href="https://rdrr.io/r/base/library.html">library()</a></code> function. Remember the solutions if needed.
<ul>
<li>Load the packages in this order, <code>car</code>,<code>correlation</code>, <code>report</code>, <code>psych</code>, and <code>tidyverse</code>
</li>
<li>we have not used four of these packages before so you will likely need to install them using <code><a href="https://rdrr.io/r/utils/install.packages.html">install.packages()</a></code>. Remember though that you should only do this on your own machine and only in the console window. If you are using the RServer you will not need to install them.</li>
</ul>
</li>
<li>Finally, load the data into an object named <code>mh</code> using <code>read_csv()</code>.</li>
</ul>
<div class="webex-solution">
<button>
Additional Hints
</button>
<div class="cell" data-layout-align="center">
<ul>
<li>Each package requires using the <code><a href="https://rdrr.io/r/base/library.html">library()</a></code> function each time. For example, <code><a href="https://r-forge.r-project.org/projects/car/">library(car)</a></code>, <code>libary(correlation)</code>, etc, etc.</li>
<li>mh &lt;- read_csv(“What_is_your_datafile_called.csv”)</li>
</ul>
</div>
</div>
</section><section id="corr-a2" class="level4" data-number="8.1.0.2"><h4 data-number="8.1.0.2" class="anchored" data-anchor-id="corr-a2">
<span class="header-section-number">8.1.0.2</span> Activity 2: Look at your data</h4>
<p>Excellent! If you have loaded in the data correctly then you should be able to have a look at it through one of the various methods we have looked at already.</p>
<ul>
<li>Look at your data using the <code><a href="https://rdrr.io/r/utils/head.html">head()</a></code> function and you should see the following:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">Participant</th>
<th style="text-align: right;">Abil</th>
<th style="text-align: right;">IQ</th>
<th style="text-align: right;">Home</th>
<th style="text-align: right;">TV</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">144</td>
<td style="text-align: right;">487</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">109</td>
<td style="text-align: right;">123</td>
<td style="text-align: right;">608</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">640</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">155</td>
<td style="text-align: right;">493</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">103</td>
<td style="text-align: right;">636</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">105</td>
<td style="text-align: right;">161</td>
<td style="text-align: right;">407</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>As you can see, we have five columns and they are:</p>
<ul>
<li>the participant number (<code>Participant</code>),</li>
<li>Reading Ability score (<code>Abil</code>),</li>
<li>Intelligence score (<code>IQ</code>),</li>
<li>the number of minutes spent reading at Home per week (<code>Home</code>),</li>
<li>and the number of minutes spent watching TV per week (<code>TV</code>).</li>
</ul>
<p>Here we will we will focus on Reading Ability and IQ but for further practice you can look at other relationships in your free time.</p>
<p>A probable <a class="glossary">hypothesis<span class="def"></span></a> for today could be that as Reading Ability increases so does Intelligence (remember there is no causality here). Or phrasing the <a class="glossary">alternative hypothesis<span class="def"></span></a> (<span class="math inline">\(H_1\)</span>) more formally, we hypothesise that the reading ability of school children, as measured through a standardized test, and intelligence, again measured through a standardized test, show a positive relationship. This is the hypothesis we will test today but remember that we could always state the <a class="glossary">null hypothesis<span class="def"></span></a> (<span class="math inline">\(H_0\)</span>) that there is no relationship between reading ability and IQ.</p>
</section></section><section id="assumptions-of-the-test" class="level2" data-number="8.2"><h2 data-number="8.2" class="anchored" data-anchor-id="assumptions-of-the-test">
<span class="header-section-number">8.2</span> Assumptions of the test</h2>
<p>Now before running an analysis we should check the <a class="glossary">assumptions<span class="def"></span></a> of the test, where the assumptions are checks that the data must pass before we can use certain tests. The assumptions change on the test and you should only use a given test based on how well the data meets the assumptions of the test. In short, the Pearson correlation and the Spearman correlation have different assumptions and we need to check our data to see which test to use.</p>
<section id="corr-a3" class="level4" data-number="8.2.0.1"><h4 data-number="8.2.0.1" class="anchored" data-anchor-id="corr-a3">
<span class="header-section-number">8.2.0.1</span> Activity 3: Assumptions</h4>
<p>For correlations, the main assumptions we need to check are:</p>
<ol type="1">
<li>Is the data interval, ratio, or ordinal?</li>
<li>Is there a data point for each participant on both variables?</li>
<li>Is the data <a class="glossary">normally distributed<span class="def"></span></a> in both variables?</li>
<li>Does the relationship between variables appear linear?</li>
<li>Does the spread have <a class="glossary">homoscedasticity<span class="def"></span></a>?</li>
</ol>
<p>We will look at each of these assumptions in turn to see which correlation we should use.</p>
<p><strong>Assumption 1: Level of Measurement</strong></p>
<p>If we want to run a Pearson correlation then we need interval or ratio data; Spearman correlations can run with ordinal, interval or ratio data. What type of data do we have?</p>
<ul>
<li>The type of data in this analysis is most probably <select class="webex-select"><option value="blank"></option>
<option value="">ratio</option>
<option value="answer">interval</option>
<option value="">ordinal</option>
<option value="">nominal</option></select> as the data is <select class="webex-select"><option value="blank"></option>
<option value="answer">continuous</option>
<option value="">discrete</option></select> and there is unlikely to be a true zero</li>
</ul>
<div class="webex-solution">
<button>
Hints on data type
</button>
<div class="cell" data-layout-align="center">
<ul>
<li>Are the variables continuous?</li>
<li>Is the difference between 1 and 2 on the scale equal to the difference between 2 and 3?</li>
</ul>
</div>
</div>
<p><strong>Assumption 2: Pairs of Data</strong></p>
<p>Great! So the data looks at least interval and continuous. Next, all correlations must have a data point for each participant in the two variables being correlated. This should make sense as to why - you can’t correlate against an empty cell! So now go check that you have a data point in both columns for each participant.</p>
<p><strong>Note:</strong> You can check for missing data by visual inspection - literally using your eyes. A missing data point will show as a NA, which is short for not applicable, not available, or no answer. An alternative would be to use the <code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code> function. This can be really handy when you have lots of data and visual inspection would just take too long. If for example you ran the following code:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">is.na</span>(mh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you look at the output from that function, each FALSE tells you that there is a data-point in that cell. That is because <code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code> asks is that cell a NA; is it empty. If the cell was empty then it would come back as TRUE. As all cells have data in them, they are all showing as FALSE. If you wanted to ask the opposite question, is their data in this cell, then you would write !is.na() which is read as “is not NA”. Remember, the exclamation mark ! turns the question into the opposite.</p>
<p>However you have looked at the data, it looks like that everyone has data in all the columns but let’s test our skills a little whilst we are here. Answer the following questions:</p>
<ol type="1">
<li>How is missing data represented in a tibble? <select class="webex-select"><option value="blank"></option>
<option value="">an empty cell</option>
<option value="answer">NA</option>
<option value="">a large number</option>
<option value="">don’t know</option></select>
</li>
<li>Which code would leave you with just the participants who were missing Reading Ability data in mh: <select class="webex-select"><option value="blank"></option>
<option value="">filter(mh, is.na(Ability)</option>
<option value="answer">filter(mh, is.na(Abil)</option>
<option value="">filter(mh, !is.na(Ability)</option>
<option value="">filter(mh, !is.na(Abil)</option></select>
</li>
<li>Which code would leave you with just the participants who were not missing Reading Ability data in mh: <select class="webex-select"><option value="blank"></option>
<option value="">filter(mh, is.na(Ability)</option>
<option value="">filter(mh, is.na(Abil)</option>
<option value="">filter(mh, !is.na(Ability)</option>
<option value="answer">filter(mh, !is.na(Abil)</option></select>
</li>
</ol>
<div class="webex-solution">
<button>
Hints on removing missing data points
</button>
<div class="cell" data-layout-align="center">
<ul>
<li>
<code>filter(dat, is.na(variable))</code> versus <code>filter(dat, !is.na(variable))</code>
</li>
</ul>
</div>
</div>
<p><strong>Assumption 3-5: Normality, linearity, homoscedasticity</strong></p>
<p>Brilliant! We know our data type and we know we have no missing data. The remaining assumptions are all best checked through visualisations. You can use histograms and QQ-plots to check that the data (<code>Abil</code> and <code>IQ</code>) are both normally distributed, and you can use a scatterplot of <code>IQ</code> as a function of <code>Abil</code> to check whether the relationship is linear, with homoscedasticity, and without outliers. An alternative would be to use z-scores to check for outliers with the cut-off usually being set at around <span class="math inline">\(\pm2.5SD\)</span> or <span class="math inline">\(\pm3SD\)</span>. You could do this using the mutate function (e.g.&nbsp;<code>mutate(z = (X - mean(X))/SD(X))</code>), but today we will just use visual checks.</p>
<p>We will now ask you to create a few figures and then we will look at them together, as a whole, to answer some questions about these last assumptions.</p>
<p><strong>Histograms for Normality</strong></p>
<ul>
<li>Type the below code in a new code chunk and run it to create a histogram for <code>Abil</code>.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mh, <span class="fu">aes</span>(<span class="at">x =</span> Abil)) <span class="sc">+</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This code should look very similar to the code you used to create a bar plot in Chapter 7. We have specified that we want to display <code>Abil</code> on the x-axis and that the shape we want to produce is a histogram, hence <code>geom_histogram()</code>. Just like <code>geom_bar()</code>, you do not need to specify the y-axis because if it’s a histogram, it’s always a count. The figure should look as shown here.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="09-correlation_files/figure-html/abil-hist-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Histogram of Abil</figcaption></figure>
</div>
</div>
</div>
<ul>
<li>Now, in a new code chunk, write and run code to produce a histogram for the variable <code>IQ</code>. Remember the solutions are at the end of the chapter.</li>
</ul>
<p><strong>Q-Q Plots for Normality</strong></p>
<p>As we said we will look at the figures in a minute but first we need a few more plots. One being the <a class="glossary">Q-Q plot<span class="def"></span></a> which allows us to check normality. The Q-Q plot require us to use the package <code>car</code> rather than <code>ggplot2</code>. You can make Q-Q plots in <code>ggplot2</code> but they aren’t as useful, however, the code is still very simple.</p>
<ul>
<li>In a new code chunk, type and run the below code to create a Q-Q plot for <code>Abil</code>.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">qqPlot</span>(<span class="at">x =</span> mh<span class="sc">$</span>Abil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This code looks a little different to code you’ve used up until this point as it comes from Base R. It uses the notation <code>object$variable</code> so our x variable could be read as “use the variable <code>Abil</code> from the object <code>mh</code>. And the figure will look like this:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="09-correlation_files/figure-html/qq-abil-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Q-Q plot for Abil</figcaption></figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15  4</code></pre>
</div>
</div>
<p>The Q-Q plot includes a <strong>confidence envelope</strong> (the blue dotted lines) around the data with the understanding that if your data points fall within these dotted lines then you can assume normality. The <code>ggplot2</code> version of Q-Q plots make it more difficult to add on this confidence envelope, which is why we’re using a different package. <code>qqPlot()</code> will also print the IDs of the most extreme data points. In this case, the 4th and 15th data point in <code>Abil</code> are flagged, although because they fall within the confidence envelope, they don’t appear problematic. This also explains why you might see a message stating <code>## [1] 15 4</code>. The 15th and 4th value are worth considering!</p>
<ul>
<li>Now, in a new code chunk, write and run code to create a Q-Q plot for <code>IQ</code>.</li>
</ul>
<p><strong>Information: Normality of the residuals</strong></p>
<p>One thing to note before we move on is that, in terms of normality, it is in fact the normality of the <a class="glossary">residuals<span class="def"></span></a> that matters, where the residuals are the difference between the individual data points and the <a class="glossary">line of best fit<span class="def"></span></a>. However, to fully understand this we need to cover more information first as introducing that concept at this stage would be confusing. One approach the field can use however is that if the data is normally distributed then it is highly likely that the residuals will also be normally distributed. We will look at residuals in the next chapter, but here we will instead use the normality of the raw data as a proxy for the normality of the residuals.</p>
<p><strong>Scatterplots for linearity and homoscedasticity</strong></p>
<p>Finally, in order to assess linearity and homoscedasticity, we can create a scatterplot using <code>ggplot2</code>.</p>
<ul>
<li>In a new code chunk, copy and run the below code to create a scatterplot of the relationship between IQ and Ability.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mh, <span class="fu">aes</span>(<span class="at">x =</span> Abil, <span class="at">y =</span> IQ)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>ggplot2</code> code is very similar to what you have already encountered with the bar chart and violin-boxplot.</p>
<ul>
<li>The first line of data sets up the base of the plot and we specify that we wish to display <code>Abil</code> on the x-axis, <code>IQ</code> on the y-axis, and use the dataset <code>mh</code>.</li>
<li>The first geom, <code>geom_point()</code>, adds in the data points,</li>
<li>the second geom, <code>geom_smooth</code>, adds in the line of best fit. The shaded area around the line is a <strong>confidence interval</strong> around the data. This can be turned off by setting <code>se = FALSE</code> as an additional argument.</li>
</ul>
<p>The figure should look as follows:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="09-correlation_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Scatterplot of scores</figcaption></figure>
</div>
</div>
</div>
<p><strong>Note:</strong> Do not worry if you see a message stating <code>## geom_smooth() using formula 'y ~ x'</code>. This is just letting you know how it is plotting the line of best fit (the blue line)</p>
<ul>
<li>Now, remembering that <code>ggplot2</code> works on layers and that you can customise each layer, edit the above code to add in a layer of <code>scale_x_continuous()</code> that changes the label <code>Abil</code> to <code>Reading Ability</code>.</li>
</ul>
<p><strong>Checking the assumptions</strong></p>
<p>Now that we have all the figures we need we should be able to check the assumptions. Try to answer the following questions, based on the above visualisations:</p>
<ul>
<li>Is the assumption of normality met for both variables? <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select>
</li>
<li>Is the assumption of linearity met? <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select>
</li>
<li>Is the assumption of homoscedasticity met? <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select>
</li>
<li>Based on the above, which correlation method would you use? <select class="webex-select"><option value="blank"></option>
<option value="answer">Pearson</option>
<option value="">Spearman</option></select>
</li>
</ul>
<div class="webex-solution">
<button>
Explain these answers
</button>
<div class="cell" data-layout-align="center">
<p>When assessing assumptions through the use of visualisations your decision will always be a judgement call. In this dataset, we only have data from 25 participants therefore it is very unlikely we would ever observe perfect normality and linearity in this dataset. It is likely that a researcher would assume that this data is approximately normal, that there is no evidence of a non-linear relationship, and that the spread of data points around the line is relatively even. Many students become fixated with needing a ‘perfect’ dataset that follows an exactly normal distribution. This is unlikely to ever happen with real data - learn to trust your instincts!</p>
<p>Finally, as the data is interval, continuous, normally distributed, and the relationship is linear and the assumption of homoscedasticity has been met, we would use a Pearson correlation.</p>
</div>
</div>
</section></section><section id="descriptives-of-the-correlation" class="level2" data-number="8.3"><h2 data-number="8.3" class="anchored" data-anchor-id="descriptives-of-the-correlation">
<span class="header-section-number">8.3</span> Descriptives of the Correlation</h2>
<p>Now that we have checked our assumptions and have confirmed we will use the Pearson correlation, the next step is descriptives. A key thing to keep in mind is that the <a class="glossary">scatterplot<span class="def"></span></a> is actually the descriptive of the correlation. Meaning that in an article, or in a report, you would not only use the scatterplot to determine which type of correlation to use but also to describe the potential relationship in regards to your hypothesis. So you would always expect to see a scatterplot in the write-up of this type of analysis.</p>
<section id="corr-a4" class="level4" data-number="8.3.0.1"><h4 data-number="8.3.0.1" class="anchored" data-anchor-id="corr-a4">
<span class="header-section-number">8.3.0.1</span> Activity 4: Descriptive statistics</h4>
<ul>
<li>Looking at the scatterplot, spend a couple of minutes thinking about and describing the relationship between Ability and IQ in terms of your hypothesis. Remember this is a descriptive analysis at this stage, so nothing is confirmed. Does the relationship appear to be as we predicted in our hypothesis? A discussion is in the solutions at the end of the chapter.</li>
</ul>
<div class="webex-solution">
<button>
Hints on discussing descriptives
</button>
<div class="cell" data-layout-align="center">
<ul>
<li>Hint 1: We hypothesised that reading ability and intelligence were positively correlated. Is that what you see in the scatterplot?</li>
<li>Hint 2: Keep in mind it is subjective at this stage.</li>
<li>Hint 3: Remember to only talk about a relationship and not a prediction. This is correlational work, not regression.</li>
<li>Hint 4: Can you say something about both the strength (weak, medium, strong) and the direction (positive, negative)?</li>
</ul>
</div>
</div>
<p>In addition to the scatterplot, it can sometimes be relevant to include means and standard deviations of scales in a correlation. It is not always relevant but, as an example, if you were measuring something like anxiety, or stress, or IQ, it can be informative to include this information to help demonstrate how your sample compares to population norms. As such we will calculate some descriptives here as it is also good practice of our data-wrangling skills.</p>
<ul>
<li>In a new code chunk, write and run code to calculate the mean score and standard deviation for <code>Abil</code> and <code>IQ</code> using <code>summarise()</code> and store the output of this function in an object called <code>descriptives</code>
<ul>
<li>Name the output of the calculations <code>Abil_mean</code>, <code>Abil_SD</code>, <code>IQ_mean</code>, and <code>IQ_SD</code>. Make sure to use these exact spellings otherwise later activities won’t work.</li>
<li>
<strong>hint:</strong> We have already seen how to calculate the <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>, the <code><a href="https://rdrr.io/r/stats/median.html">median()</a></code>, the number of people (with <code>n()</code>), and the <code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code> within the <code>summarise()</code> function. Other descriptives such as the <code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code>, the <code><a href="https://rdrr.io/r/base/Extremes.html">min()</a></code> and the <code><a href="https://rdrr.io/r/base/Extremes.html">max()</a></code> can also be calculated in a similar way to using <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> and <code><a href="https://rdrr.io/r/stats/median.html">median()</a></code>.</li>
</ul>
</li>
</ul>
<p>If you have performed this correctly, when you view <code>descriptives</code> should look similar to this:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: center;">Abil_mean</th>
<th style="text-align: center;">Abil_SD</th>
<th style="text-align: center;">IQ_mean</th>
<th style="text-align: center;">IQ_SD</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: center;">55.12</td>
<td style="text-align: center;">6.08</td>
<td style="text-align: center;">100.04</td>
<td style="text-align: center;">9.04</td>
</tr></tbody>
</table>
</div>
</div>
<p>Answer the following questions to confirm your understanding of the output:</p>
<ul>
<li>What is the mean of Reading Ability? <select class="webex-select"><option value="blank"></option>
<option value="">54.12</option>
<option value="">56.12</option>
<option value="answer">55.12</option></select>
</li>
<li>What is the mean of IQ? <select class="webex-select"><option value="blank"></option>
<option value="">99.04</option>
<option value="answer">100.04</option>
<option value="">101.04</option></select>
</li>
<li>If the population norm mean of IQ is 100, how comparable is your sample to the population? <select class="webex-select"><option value="blank"></option>
<option value="answer">the same</option>
<option value="">very different</option></select>
</li>
</ul></section></section><section id="inferentials-of-the-correlation" class="level2" data-number="8.4"><h2 data-number="8.4" class="anchored" data-anchor-id="inferentials-of-the-correlation">
<span class="header-section-number">8.4</span> Inferentials of the correlation</h2>
<p>Excellent! So we have checked our assumptions and our descriptives. Our data looks consistent with population norms and the scatterplot would suggest a positive relationship between the two variables. Finally we will run the correlation!</p>
<p>There are often many different functions that can be used to achieve the same thing and we’re actually going to show you two ways of running a correlation as some people prefer one approach over the other because of the data type the results come in and how easy it is to work with that output.</p>
<section id="corr-a5" class="level4" data-number="8.4.0.1"><h4 data-number="8.4.0.1" class="anchored" data-anchor-id="corr-a5">
<span class="header-section-number">8.4.0.1</span> Activity 5: Run the correlation</h4>
<p>First, we’ll use the <code>correlation()</code> function from the <code>correlation</code> package. Remember that for help on any function you can type e.g., <code>?correlation</code> in the console window. The <code>correlation()</code> function requires:</p>
<ul>
<li>The name of the data set you are using</li>
<li>The name of the first variable you want to select for the correlation</li>
<li>The name of the second variable you want to select for the correlation</li>
<li>The type of correlation you want to run: e.g.&nbsp;<code>pearson</code>, <code>spearman</code>
</li>
<li>The type of NHST tail you want to run: e.g.&nbsp;<code>"less"</code>,<code>"greater"</code>, <code>"two.sided"</code>
</li>
</ul>
<p>For example, if your data is stored in <code>dat</code> and you want to do a two-sided pearson correlation of the variables (columns) <code>X</code> and <code>Y</code>, then you would do:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">correlation</span>(<span class="at">data =</span> dat, </span>
<span id="cb7-2"><a href="#cb7-2"></a>            <span class="at">select =</span> <span class="st">"X"</span>, </span>
<span id="cb7-3"><a href="#cb7-3"></a>            <span class="at">select2 =</span> <span class="st">"Y"</span>,  </span>
<span id="cb7-4"><a href="#cb7-4"></a>            <span class="at">method =</span> <span class="st">"pearson"</span>, </span>
<span id="cb7-5"><a href="#cb7-5"></a>            <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here we are wanting to run a Pearson correlation with a two-sided alternative.</p>
<ul>
<li>In a new code chunk, using the information about <code>correlation()</code> above, type and run a Pearson correlation between IQ and Ability and store the output in an object called <code>results</code>.</li>
<li>View the output by typing <code>View(results)</code> in the console window</li>
</ul>
<p>The second method is to use <code><a href="https://rdrr.io/r/stats/cor.test.html">cor.test()</a></code> which is a <strong><code>Base R</code></strong> function and uses similar code as <code>correlation()</code> except for how the variables are specified. <code><a href="https://rdrr.io/r/stats/cor.test.html">cor.test()</a></code> use the same <code>object$variable</code> syntax we saw in <code>qqPlot()</code>:</p>
<ul>
<li>In a new code chunk, type and run the below code and then view the output by typing <code>results2</code> in the console.
<ul>
<li>not that we have specified <code>x = mh$IQ</code> meaning that the first variable, x, is the column <code>IQ</code> in the object <code>mh</code>.</li>
</ul>
</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>results2 <span class="ot">&lt;-</span>  <span class="fu">cor.test</span>(<span class="at">x =</span> mh<span class="sc">$</span>IQ, </span>
<span id="cb8-2"><a href="#cb8-2"></a>                      <span class="at">y =</span> mh<span class="sc">$</span>Abil, </span>
<span id="cb8-3"><a href="#cb8-3"></a>                      <span class="at">method =</span> <span class="st">"pearson"</span>, </span>
<span id="cb8-4"><a href="#cb8-4"></a>                      <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Look at how the output differs from <code>results</code>. We’ll come back to why we’ve shown you two ways shortly.</p>
</section></section><section id="interpreting-output-and-writing-up" class="level2" data-number="8.5"><h2 data-number="8.5" class="anchored" data-anchor-id="interpreting-output-and-writing-up">
<span class="header-section-number">8.5</span> Interpreting output and writing up</h2>
<p>Excellent work. As you can see, running the correlation is actually really quick, and the hard work was checking the assumptions and some data-wrangling. You should now have a tibble called <code>results</code> that gives you the output of the correlation between Reading Ability and IQ for the school children measured in Miller and Haden (2013) Chapter 11. All that is left to do now is interpret the output and write it up.</p>
<section id="corr-a6" class="level4" data-number="8.5.0.1"><h4 data-number="8.5.0.1" class="anchored" data-anchor-id="corr-a6">
<span class="header-section-number">8.5.0.1</span> Activity 6: Interpreting the correlation</h4>
<p>Look at <code>results</code> and then answer the following questions:</p>
<ol type="1">
<li>What is the value of Pearson’s <em>r</em> to 2 decimal places? <input class="webex-solveme nospaces" size="20" data-answer="[&quot;.45&quot;,&quot;0.45&quot;]">
</li>
<li>The direction of the relationship between Ability and IQ is: <select class="webex-select"><option value="blank"></option>
<option value="answer">positive</option>
<option value="">negative</option>
<option value="">no relationship</option></select>
</li>
<li>The strength of the relationship between Ability and IQ is: <select class="webex-select"><option value="blank"></option>
<option value="">strong</option>
<option value="answer">medium</option>
<option value="">weak</option></select>
</li>
<li>Assuming <span class="math inline">\(\alpha = .05\)</span> the relationship between Ability and IQ is: <select class="webex-select"><option value="blank"></option>
<option value="answer">significant</option>
<option value="">not significant</option></select>
</li>
<li>The alternative hypothesis was that the reading ability of school children, as measured through a standardized test, and intelligence, again through a standardized test, are positively correlated. Based on the results we can say that the alternative hypothesis: <select class="webex-select"><option value="blank"></option>
<option value="answer">is accepted</option>
<option value="">is rejected</option>
<option value="">is proven</option>
<option value="">is not proven</option></select>
</li>
</ol>
<div class="webex-solution">
<button>
Explain these answers
</button>
<div class="cell" data-layout-align="center">
<ol type="1">
<li>The test statistic, in this case the r value, is usually labelled as the <code>estimate</code>.</li>
<li>If Y increases as X increases then the relationship is positive. If Y increases as X decreases then the relationship is negative. If there is no change in Y as X changes then there is no relationship</li>
<li>Depending on the field most correlation values greater than .5 would be strong; .3 to .5 as medium, and .1 to .3 as small.</li>
<li>The field standard says less than .05 is significant and our p-value is less than .05.</li>
<li>The alternative hypothesis can only be accepted or rejected, never proven. In this case, our results matched our alternative hypothesis and therefore it is accepted. Remember that the null hypothesis on the other hand can only be rejected or retained.</li>
</ol>
</div>
</div>
</section><section id="corr-a7" class="level4" data-number="8.5.0.2"><h4 data-number="8.5.0.2" class="anchored" data-anchor-id="corr-a7">
<span class="header-section-number">8.5.0.2</span> Activity 7: Write-up</h4>
<p>Now we have interpreted the output we would want to write it up. Copy and paste the below <strong>exactly</strong> into <strong>white space</strong> in your R Markdown document and then knit the file.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>As shown <span class="cf">in</span> Figure <span class="fl">7.5</span>, there appeared to be a positive relationship between Reading <span class="fu">Ability</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r round(pluck(descriptives$Abil_mean),2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r round(pluck(descriptives$Abil_SD),2)</span><span class="st">`</span>) and <span class="fu">IQ</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r round(pluck(descriptives$IQ_mean),2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r round(pluck(descriptives$IQ_SD),2)</span><span class="st">`</span>), <span class="cf">in</span> line with the alternative hypothesis. A Pearson correlation found a significant, medium positive correlation between the two <span class="fu">variables</span> (<span class="fu">r</span> (<span class="st">`</span><span class="at">r results$df_error</span><span class="st">`</span>) <span class="ot">=</span> <span class="st">`</span><span class="at">r round(results$r, 2)</span><span class="st">`</span>, <span class="sc">*</span>p<span class="sc">*</span> <span class="er">=</span> <span class="st">`</span><span class="at">r round(results$p, 3)</span><span class="st">`</span>) and the alternative hypothesis is therefore accepted. </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When you knit the code, assuming you have done all of the above tasks correctly, the code you pasted will transform into a readable passage as follows:</p>
<p>As shown in Figure 7.5, there appeared to be a positive relationship between Reading Ability (M = 55.12, SD = 6.08) and IQ (M = 100.04, SD = 9.04), in line with the alternative hypothesis. A Pearson correlation found a significant, medium positive correlation between the two variables (r (23) = 0.45, <em>p</em> = 0.024) and the alternative hypothesis is therefore accepted.</p>
<p>So you get a fairly ok start of a write-up. It isn’t perfect but it is a good start. For instance, the r-value should not have the first 0 and just be r = .xx. Likewise, the p-value should not have the first 0 either. So you will always have to do a bit of tidying up.</p>
<p><strong>Note:</strong> Remember that a relationship is said to be <a class="glossary">significant<span class="def"></span></a> if the p-value of the relationship is lower than the accepted level (normally called <a class="glossary">alpha<span class="def">The threshold chosen in Neyman-Pearson hypothesis testing to distinguish test results that lead to the decision to reject the null hypothesis, or not, based on the desired upper bound of the Type 1 error rate. An alpha level of 5% it most commonly used, but other alpha levels can be used as long as they are determined and preregistered by the researcher before the data is analyzed.</span></a> and set at <span class="math inline">\(\alpha = .05\)</span>). Alternatively, a relationship that has a p-value higher than the accepted level is said to be <a class="glossary">non significant<span class="def"></span></a></p>
<p><strong>But why two approaches</strong></p>
<p>The reason that we have shown you two methods of performing correlations is because of the way each outputs the results. <code>correlation()</code> produces a tibble which means it is very easy to work with and pull out values or join to another table as needed because it is already in tidyverse format. <code><a href="https://rdrr.io/r/stats/cor.test.html">cor.test()</a></code> on the other hand produces a <code>list</code> type object, which is a harder to work with. However, the output of <code><a href="https://rdrr.io/r/stats/cor.test.html">cor.test()</a></code> also happens to work with functions from the <code>report</code> package, <code>report()</code> and <code>report_table()</code> that give you an automatic report of the analyses. For example, <code>report()</code> presents a fixed write-up of the correlation with all the available information. For correlations, this is perhaps less than useful, however, for more complex statistics this reporting function can really help when learning about data and output, and so we’re introducing it now. <code>report()</code> doesn’t currently work with the output of <code>correlation()</code> which is why we showed you both ways. Run the below in your console window and you will see what we mean - you will probably get an error.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">report</span>(results2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Note:</strong> The write-up that comes out of report should not be considered as something to copy and paste into a report. It is a means of just obtaining an overview quickly to help you confirm your own thinking. There are issues again with the presentation of numbers and writing, and additional info that isn’t needed. Basically, use these functions and approaches to start you off in your writing, but not as your write-up.</p>
</section></section><section id="multiple-correlations" class="level2" data-number="8.6"><h2 data-number="8.6" class="anchored" data-anchor-id="multiple-correlations">
<span class="header-section-number">8.6</span> Multiple Correlations</h2>
<p>Finally, to round off this chapter, we want to briefly show you about running multiple correlations at one. Above we ran one correlation. However, when you have lots of variables in a dataset, to get a quick overview of patterns, you might want to run all the correlations at the same time or create a matrix of scatterplots at the one time. You can do this with functions from the <code>psych</code> and <code>correlation</code> packages (<code><a href="https://rdrr.io/r/stats/cor.test.html">cor.test()</a></code> only works for one correlation at a time). We will use the Miller and Haden data here again which you should still have in a tibble called <code>mh</code>.</p>
<section id="corr-a8" class="level4" data-number="8.6.0.1"><h4 data-number="8.6.0.1" class="anchored" data-anchor-id="corr-a8">
<span class="header-section-number">8.6.0.1</span> Activity 8: Scatterplot matrix</h4>
<ul>
<li>In a new code chunk, type and run the following code. The <code>pairs.panels())</code> function comes from the <code>psych</code> library and creates a matrix of scatterplots, with the histograms, and correlation coefficients which you can then use to give you an overview of all the relationships at the one time. So it is useful for checking assumptions in one place.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">pairs.panels</span>(mh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="09-correlation_files/figure-html/pairs-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Scatterplot matrix</figcaption></figure>
</div>
</div>
</div>
<p>Notice something wrong? <code>pairs.panels()</code> will create plots for <strong>all</strong> variables in your data (as will <code>correlation()</code> below). This means that it has correlated the Participant ID number as well, which is totally meaningless.</p>
<p>Instead, we can use pipes to help us out here. The code below:</p>
<ul>
<li>Takes the dataset <code>mh</code> and then;</li>
<li>Uses <code>select()</code> to get rid of the <code>Participant</code> column and then;</li>
<li>Pipes the remaining data into the <code>pairs.panels()</code> function</li>
<li>The additional arguments:
<ul>
<li>
<code>ellipses = FALSE</code> turns off the <a href="https://analyse-it.com/docs/user-guide/multivariate/scatter-plot#:~:text=If%20the%20association%20is%20a,more%20the%20variables%20are%20uncorrelated." target="_blank">correlation ellipses</a>,</li>
<li>
<code>lm = TRUE</code> use a linear line of best fit,</li>
<li>`method = “pearson”, specifies a Pearson correlation.</li>
</ul>
</li>
</ul>
<p>There are additional arguments to adjust the plot <code>pairs.panel</code> creates that you can look up in the help documentation if you are interested.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>mh <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>  <span class="fu">select</span>(<span class="sc">-</span>Participant) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3"></a>  <span class="fu">pairs.panels</span>(<span class="at">ellipses =</span> <span class="cn">FALSE</span>, </span>
<span id="cb12-4"><a href="#cb12-4"></a>               <span class="at">lm =</span> <span class="cn">TRUE</span>, </span>
<span id="cb12-5"><a href="#cb12-5"></a>               <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Which produces:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="09-correlation_files/figure-html/pairs-pipes-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Adjusted scatterplot matrix</figcaption></figure>
</div>
</div>
</div>
</section><section id="corr-a9" class="level4" data-number="8.6.0.2"><h4 data-number="8.6.0.2" class="anchored" data-anchor-id="corr-a9">
<span class="header-section-number">8.6.0.2</span> Activity 9: Running multiple correlations</h4>
<p>To perform multiple correlations in one go, we will again use the <code>correlation()</code> function. package. Rather than specifying two variables to correlation, you can also provide a data frame that has multiple variables and it will run all possible correlations between the variables. Similar to above, we want to remove the <code>Participant</code> column before we do this.</p>
<ul>
<li><p><code>method</code> controls which correlation is computed, the default is <code>pearson</code> but if you needed to run the non-parametric version you could change this to <code>spearman</code>.<br></p></li>
<li>
<p><code>p_adjust</code> is the reason we are using the <code>correlation</code> package. In the lectures we discussed the problem of <a class="glossary">multiple comparisons<span class="def"></span></a> - the idea that if you run lots and lots of tests your false positive rate will increase and the probability of finding a significant result increase.</p>
<ul>
<li>This argument applies a correction to the p-value that adjusts for the number of correlations you have performed. There are several different methods which you can look up in the help documentation, but here we are setting <a class="glossary">bonferroni<span class="def"></span></a>. The default setting is actually the less <a class="glossary">conservative analysis<span class="def"></span></a> <a class="glossary">Holm-Bonferroni<span class="def"></span></a> and you can read about why some might chose that instead in the help function by typing <code>?correlation</code> in the console window.</li>
</ul>
</li>
<li><p><strong>Note:</strong> Because you’re running multiple correlations and some may be positive and some may be negative, there is no option to specify a one or two-tailed test.</p></li>
<li><p>Run the below code to calculate then view the correlation results</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>corr_results <span class="ot">&lt;-</span> mh <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2"></a>  <span class="fu">select</span>(<span class="sc">-</span>Participant) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3"></a>  <span class="fu">correlation</span>(<span class="at">method =</span> <span class="st">"pearson"</span>, </span>
<span id="cb13-4"><a href="#cb13-4"></a>              <span class="at">p_adjust =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb13-5"><a href="#cb13-5"></a></span>
<span id="cb13-6"><a href="#cb13-6"></a>corr_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Which produces the following output:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(corr_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 17%">
<col style="width: 5%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: left;">Parameter2</th>
<th style="text-align: right;">r</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">df_error</th>
<th style="text-align: right;">p</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">n_Obs</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Abil</td>
<td style="text-align: left;">IQ</td>
<td style="text-align: right;">0.4511699</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.0681965</td>
<td style="text-align: right;">0.7182564</td>
<td style="text-align: right;">2.4245212</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.1415557</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abil</td>
<td style="text-align: left;">Home</td>
<td style="text-align: right;">0.7443192</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.4946735</td>
<td style="text-align: right;">0.8804938</td>
<td style="text-align: right;">5.3451643</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.0001194</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Abil</td>
<td style="text-align: left;">TV</td>
<td style="text-align: right;">-0.2881974</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.6134691</td>
<td style="text-align: right;">0.1206755</td>
<td style="text-align: right;">-1.4433874</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.9743671</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">IQ</td>
<td style="text-align: left;">Home</td>
<td style="text-align: right;">0.2016786</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.2102033</td>
<td style="text-align: right;">0.5527604</td>
<td style="text-align: right;">0.9875083</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IQ</td>
<td style="text-align: left;">TV</td>
<td style="text-align: right;">0.2455425</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.1656610</td>
<td style="text-align: right;">0.5840118</td>
<td style="text-align: right;">1.2147699</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">Home</td>
<td style="text-align: left;">TV</td>
<td style="text-align: right;">-0.6476572</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.8303052</td>
<td style="text-align: right;">-0.3393758</td>
<td style="text-align: right;">-4.0765523</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.0027905</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">25</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>corr_results</code> is a tibble that lists the results of each correlation with its corresponding statistics. Look through the table and then answer the following questions:</p>
<ol type="1">
<li>Is the correlation between <code>Abil</code> and <code>Home</code> positive or negative? <select class="webex-select"><option value="blank"></option>
<option value="answer">Positive</option>
<option value="">Negative</option></select>
</li>
<li>This means that as <code>Abil</code> scores increase, <code>Home</code> scores will <select class="webex-select"><option value="blank"></option>
<option value="answer">Increase</option>
<option value="">Decrease</option></select>
</li>
<li>What is the strongest positive correlation? <select class="webex-select"><option value="blank"></option>
<option value="">Abil * IQ</option>
<option value="answer">Abil * Home</option>
<option value="">Abil * TV</option></select>
</li>
<li>What is the strongest negative correlation? <select class="webex-select"><option value="blank"></option>
<option value="">Abil * TV</option>
<option value="">IQ * TV</option>
<option value="answer">Home * TV</option></select>
</li>
<li>Is the correlation between <code>Abil</code> and <code>IQ</code> significant? <select class="webex-select"><option value="blank"></option>
<option value="">Yes</option>
<option value="answer">No</option></select>
</li>
<li>Is the correlation between <code>Abil</code> and <code>Home</code> significant? <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select>
</li>
<li>How would you describe the strength of the correlation between <code>Home</code> and <code>TV</code>? <select class="webex-select"><option value="blank"></option>
<option value="">Weak</option>
<option value="">Medium</option>
<option value="answer">Strong</option></select>
</li>
<li>Think back to the lecture. Why are we not calculating an effect size?</li>
</ol>
<div class="webex-solution">
<button>
Explain these answers
</button>
<div class="cell" data-layout-align="center">
<ol type="1">
<li>Negative correlations are denoted by a negative r value.
<ol start="2" type="1">
<li>Positive correlations mean that as one score goes up so does the other, negative correlations mean that as one score goes up the other goes down.<br>
3 &amp; 4. Remember that correlations take values from -1 - 1 and that the nearer to one in either direction the stronger the correlation (i.e., an r value of 0 would demonstrate a lack of any relationship.<br>
5 &amp; 6. The traditional cut-off for significance is .05. Anything below .05 is considered significant. Be careful to pay attention to decimal places.<br>
</li>
<li>Cohen’s guidelines recommend weak = 1. - .3, medium = .3 - .5, strong &gt; .5.<br>
</li>
<li>Because r is an effect size.</li>
</ol>
</li>
</ol>
</div>
</div>
<p>Nice work! So it can be really easy to run a lot of correlations at once. However, you need to remember about what is appropriate in research. You should not just wildly run every correlation you can and then write up your favourite. PreRegistration of ideas, or Registered Reports, helps reduce Questionable Research Practices, and this is just another example of where setting out in advance, what you plan to do, will prevent bad practice!</p>
</section></section><section id="corr-fin" class="level2" data-number="8.7"><h2 data-number="8.7" class="anchored" data-anchor-id="corr-fin">
<span class="header-section-number">8.7</span> Finished!</h2>
<p>Excellent work today! You can now add running, interpreting and writing up correlations to the list of knowledge and skills in your research methods toolbox. Remember that actually a lot of the work is in the preparation of the data and really running the correlation is just one more function. It might be worthwhile repeating the first few activities with two other variables to test your understanding. If you have any questions, please post them on Teams.</p>
</section><section id="test-yourself" class="level2" data-number="8.8"><h2 data-number="8.8" class="anchored" data-anchor-id="test-yourself">
<span class="header-section-number">8.8</span> Test Yourself</h2>
<p>Look at this code and answer the following questions:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a>results <span class="ot">&lt;-</span> <span class="fu">correlation</span>(<span class="at">data =</span> mh, </span>
<span id="cb15-2"><a href="#cb15-2"></a>                       <span class="at">select =</span> <span class="st">"IQ"</span>, </span>
<span id="cb15-3"><a href="#cb15-3"></a>                       <span class="at">select2 =</span> <span class="st">"Home"</span>,  </span>
<span id="cb15-4"><a href="#cb15-4"></a>                       <span class="at">method =</span> <span class="st">"pearson"</span>, </span>
<span id="cb15-5"><a href="#cb15-5"></a>                       <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li>What would this analysis show?
<div id="radio_YATEPMSUDY" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_YATEPMSUDY" value=""><span>the relationship between IQ and the time spent watching TV at home</span></label><label><input type="radio" autocomplete="off" name="radio_YATEPMSUDY" value=""><span>the effect of IQ on time spent reading at Home</span></label><label><input type="radio" autocomplete="off" name="radio_YATEPMSUDY" value="answer"><span>the relationship between IQ and the time spent reading at home</span></label><label><input type="radio" autocomplete="off" name="radio_YATEPMSUDY" value=""><span>the relationship between IQ and Reading Ability</span></label>
</div>
</li>
<li>What type of correlation analysis is it?
<div id="radio_SEGTQPYDQO" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_SEGTQPYDQO" value=""><span>two-tailed spearman analysis</span></label><label><input type="radio" autocomplete="off" name="radio_SEGTQPYDQO" value=""><span>one-tailed pearson analysis</span></label><label><input type="radio" autocomplete="off" name="radio_SEGTQPYDQO" value="answer"><span>two-tailed pearson analysis</span></label><label><input type="radio" autocomplete="off" name="radio_SEGTQPYDQO" value=""><span>one-tailed spearman analysis</span></label>
</div>
</li>
</ol>
<p>Now try running the code and then answering the following questions.</p>
<ol start="3" type="1">
<li>To three decimal places, what is the r-value of the correlation between IQ and the time spent reading at Home?
<div id="radio_EGQCJKDGRD" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_EGQCJKDGRD" value=""><span>0.334</span></label><label><input type="radio" autocomplete="off" name="radio_EGQCJKDGRD" value=""><span>0.553</span></label><label><input type="radio" autocomplete="off" name="radio_EGQCJKDGRD" value=""><span>0.988</span></label><label><input type="radio" autocomplete="off" name="radio_EGQCJKDGRD" value="answer"><span>0.202</span></label>
</div>
</li>
<li>To three decimal places, what is the p-value of the correlation between IQ and the time spent reading at Home?
<div id="radio_RYHQTNDQKH" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_RYHQTNDQKH" value=""><span>0.988</span></label><label><input type="radio" autocomplete="off" name="radio_RYHQTNDQKH" value="answer"><span>0.334</span></label><label><input type="radio" autocomplete="off" name="radio_RYHQTNDQKH" value=""><span>0.553</span></label><label><input type="radio" autocomplete="off" name="radio_RYHQTNDQKH" value=""><span>0.202</span></label>
</div>
</li>
<li>What is the degrees of freedom of the correlation between IQ and the time spent reading at Home?
<div id="radio_ZIGMLDNOMA" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_ZIGMLDNOMA" value="answer"><span>23</span></label><label><input type="radio" autocomplete="off" name="radio_ZIGMLDNOMA" value=""><span>25</span></label><label><input type="radio" autocomplete="off" name="radio_ZIGMLDNOMA" value=""><span>0.553</span></label><label><input type="radio" autocomplete="off" name="radio_ZIGMLDNOMA" value=""><span>0.988</span></label>
</div>
</li>
</ol>
<div class="webex-solution">
<button>
Explain these answers
</button>
<div class="cell" data-layout-align="center">
<p>This analysis is a two-tailed pearson correlation looking at the relationship between IQ and the amount of time spent reading at home. You can tell this from the two variables in the code being IQ and Home, and the code stating pearson, and two-sided (another name for two-tailed). If you run the analysis you will find that the result would be r(23) = .202, p = .334.</p>
</div>
</div>
</section><section id="corr-sols" class="level2" data-number="8.9"><h2 data-number="8.9" class="anchored" data-anchor-id="corr-sols">
<span class="header-section-number">8.9</span> Activity solutions</h2>
<p>Below you will find the solutions to the above questions. Only look at them after giving the questions a good try and trying to find help on Google or Teams about any issues.</p>
<section id="corr-a1sol" class="level4" data-number="8.9.0.1"><h4 data-number="8.9.0.1" class="anchored" data-anchor-id="corr-a1sol">
<span class="header-section-number">8.9.0.1</span> Activity 1</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">library</span>(car)</span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="fu">library</span>(correlation)</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="fu">library</span>(report)</span>
<span id="cb16-4"><a href="#cb16-4"></a><span class="fu">library</span>(psych)</span>
<span id="cb16-5"><a href="#cb16-5"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb16-6"><a href="#cb16-6"></a>mh <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"MillerHadenData.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="corr-a3sol" class="level4" data-number="8.9.0.2"><h4 data-number="8.9.0.2" class="anchored" data-anchor-id="corr-a3sol">
<span class="header-section-number">8.9.0.2</span> Activity 3</h4>
<p><strong>The histogram of IQ</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mh, <span class="fu">aes</span>(<span class="at">x =</span> IQ)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>The qqPlot of IQ</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">qqPlot</span>(<span class="at">x =</span> mh<span class="sc">$</span>IQ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="09-correlation_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  3 14</code></pre>
</div>
</div>
<p><strong>The scatterplot</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mh, <span class="fu">aes</span>(<span class="at">x =</span> Abil, <span class="at">y =</span> IQ)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)<span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">name =</span> <span class="st">"Reading Ability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="09-correlation_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="corr-a4sol" class="level4" data-number="8.9.0.3"><h4 data-number="8.9.0.3" class="anchored" data-anchor-id="corr-a4sol">
<span class="header-section-number">8.9.0.3</span> Activity 4</h4>
<p><strong>The scatterplot</strong></p>
<p>Based on the scatterplot we might suggest that as reading ability scores increase, IQ scores also increase and as such it would appear that our data is inline with our hypothesis that the two variables are positively correlated. This appears to be a medium strength relationship.</p>
<p><strong>The means and standard deviations</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>descriptives <span class="ot">&lt;-</span> <span class="fu">summarise</span>(mh, </span>
<span id="cb22-2"><a href="#cb22-2"></a>                          <span class="at">Abil_mean =</span> <span class="fu">mean</span>(Abil),</span>
<span id="cb22-3"><a href="#cb22-3"></a>                          <span class="at">Abil_SD =</span> <span class="fu">sd</span>(Abil),</span>
<span id="cb22-4"><a href="#cb22-4"></a>                          <span class="at">IQ_mean =</span> <span class="fu">mean</span>(IQ),</span>
<span id="cb22-5"><a href="#cb22-5"></a>                          <span class="at">IQ_SD =</span> <span class="fu">sd</span>(IQ))</span>
<span id="cb22-6"><a href="#cb22-6"></a></span>
<span id="cb22-7"><a href="#cb22-7"></a>descriptives</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">Abil_mean</th>
<th style="text-align: right;">Abil_SD</th>
<th style="text-align: right;">IQ_mean</th>
<th style="text-align: right;">IQ_SD</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">55.12</td>
<td style="text-align: right;">6.084954</td>
<td style="text-align: right;">100.04</td>
<td style="text-align: right;">9.043782</td>
</tr></tbody>
</table>
</div>
</div>
</div>
</section><section id="corr-a5sol" class="level4" data-number="8.9.0.4"><h4 data-number="8.9.0.4" class="anchored" data-anchor-id="corr-a5sol">
<span class="header-section-number">8.9.0.4</span> Activity 5</h4>
<p><strong>The correlation using <code>correlation()</code></strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a>results <span class="ot">&lt;-</span> <span class="fu">correlation</span>(<span class="at">data =</span> mh, </span>
<span id="cb23-2"><a href="#cb23-2"></a>                       <span class="at">select =</span> <span class="st">"IQ"</span>, </span>
<span id="cb23-3"><a href="#cb23-3"></a>                       <span class="at">select2 =</span> <span class="st">"Abil"</span>,  </span>
<span id="cb23-4"><a href="#cb23-4"></a>                       <span class="at">method =</span> <span class="st">"pearson"</span>, </span>
<span id="cb23-5"><a href="#cb23-5"></a>                       <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span>
<span id="cb23-6"><a href="#cb23-6"></a></span>
<span id="cb23-7"><a href="#cb23-7"></a>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 18%">
<col style="width: 5%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: left;">Parameter2</th>
<th style="text-align: right;">r</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">df_error</th>
<th style="text-align: right;">p</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">n_Obs</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">IQ</td>
<td style="text-align: left;">Abil</td>
<td style="text-align: right;">0.4511699</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.0681965</td>
<td style="text-align: right;">0.7182564</td>
<td style="text-align: right;">2.424521</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.0235926</td>
<td style="text-align: left;">Pearson correlation</td>
<td style="text-align: right;">25</td>
</tr></tbody>
</table>
</div>
</div>
</div>
</section></section><section id="words-from-this-chapter" class="level2" data-number="8.10"><h2 data-number="8.10" class="anchored" data-anchor-id="words-from-this-chapter">
<span class="header-section-number">8.10</span> Words from this Chapter</h2>
<p>Below you will find a list of words that were used in this chapter that might be new to you in case it helps to have somewhere to refer back to what they mean. The links in this table take you to the entry for the words in the <a href="https://psyteachr.github.io/glossary/" target="_blank">PsyTeachR Glossary</a>. Note that the Glossary is written by numerous members of the team and as such may use slightly different terminology from that shown in the chapter.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">alpha</td>
<td style="text-align: left;">The threshold chosen in Neyman-Pearson hypothesis testing to distinguish test results that lead to the decision to reject the null hypothesis, or not, based on the desired upper bound of the Type 1 error rate. An alpha level of 5% it most commonly used, but other alpha levels can be used as long as they are determined and preregistered by the researcher before the data is analyzed.</td>
</tr>
<tr class="even">
<td style="text-align: left;">alternative hypothesis</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">assumptions</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">bonferroni</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">conservative analysis</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">correlation</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Holm-Bonferroni</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">homoscedasticity</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">hypothesis</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">inferential</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">line of best fit</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">multiple comparisons</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">negative relationship</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">non significant</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">normal distribution</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">null hypothesis</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pearson</td>
<td style="text-align: left;">a standardised measure of the linear relationship between two variables</td>
</tr>
<tr class="even">
<td style="text-align: left;">positive relationship</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q-Q plot</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">residual</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">scatterplot</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">significant</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Spearman</td>
<td style="text-align: left;">a standardised measure of the relationship between two variables that does not assume a linear relationship. Note that the relationship can be linear but it is not required.</td>
</tr>
<tr class="even">
<td style="text-align: left;">variable</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>That is end of this chapter. Be sure to look again at anything you were unsure about and make some notes to help develop your own knowledge and skills. It would be good to write yourself some questions about what you are unsure of and see if you can answer them later or speak to someone about them. Good work today!</p>


</section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script>
// open rdrr links externally ----

var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");
var exlink_func = function(){
  window.open(this.href);
  return false;
};
for (var i = 0; i < exlinks.length; i++) {
    exlinks[i].addEventListener('click', exlink_func, false);
}

// visible second sidebar in mobile ----

function move_sidebar() {
  var toc = document.getElementById("TOC");
  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");
  var right_sidebar = document.getElementById("quarto-margin-sidebar");

  if (window.innerWidth < 768) {
    small_sidebar.append(toc);
  } else {
    right_sidebar.append(toc);
  }
}
move_sidebar();
window.onresize = move_sidebar;
</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./07-data-viz.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Intro to Data Visualisation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-t-tests.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">t-tests</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">CC-BY (2024) James Bartlett &amp; Wil Toivo</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>